name: supr_face_pile
version: 1.0.0
publish_to: https://onepub.dev/api/nuvvuhnofl/
description: Package created following the video tutorial from SuprDeclarative
repository: https://github.com/talamaska/supr_face_pile
environment:
  sdk: '>=2.15.1 <3.0.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter: null
